// Config Actions
export const CHARGER_PRORITY_CHANGED = 'CHARGER_PRORITY_CHANGED';
export const OUTPUT_PRIORITY_CHANGED = 'OUTPUT_PRIORITY_CHANGED';
export const MAX_CHARGE_CURRENT_CHANGED = "MAX_CHARGE_CURRENT_CHANGED";
export const MAX_GRID_CHARGE_CURRENT_CHANGED = "MAX_GRID_CHARGE_CURRENT_CHANGED";
export const ALL_CONFIGS_FETCHED = "ALL_CONFIGS_FETCHED" 